{% set name = "py-libnuma" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9d67ad04f274015e9acac497d642ce92f8a96d1d4e7be24e39124b24320b95a 

build:
  skip: true # [py<310 or (not linux)]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation


requirements:
  build:
    
  host:
    - python
    - setuptools
    - pip
    - libnuma {{ libnuma }}
  run:
    - python
    - libnuma {{ libnuma }}


test:
  imports:
    - numa
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/eedalong/pynuma
  summary: Python3 interface to libnuma on Linux
  description: |
    py-libnuma is python3 interface to numa Linux library so that you can 
    set task affinity and memory affinity in python level for your process 
    which can help you to improve your code's performence.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/eedalong/pynuma
  doc_url: https://github.com/eedalong/pynuma
 

